<?php

namespace App\Services\Ais;

use App\Models\AisReportExport;
use App\Models\AisReportRun;
use App\Models\AuditLog;
use App\Models\User;
use App\Support\ActivityRecorder;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Collection;
use Symfony\Component\HttpFoundation\StreamedResponse;

/** Generates immutable, scope-pinned AIS analytical reports and exports. */
class AisReportService
{
    public const SOURCE_QUERY_VERSION = 'AIS-3-v1';

    /** @var array<string, array<string, mixed>> */
    public const REPORTS = [
        'portfolio-overview' => [
            'title' => 'AIS Portfolio Overview',
            'description' => 'Scope-aware headline indicators across IAP, AEMS, CMS, and ARMIS.',
            'columns' => [
                ['key' => 'indicator', 'label' => 'Indicator'],
                ['key' => 'value', 'label' => 'Value'],
                ['key' => 'source', 'label' => 'Source'],
                ['key' => 'interpretation', 'label' => 'Interpretation'],
            ],
        ],
        'status-register' => [
            'title' => 'AIS Status Register',
            'description' => 'Current status and outcome distributions from authorized source modules.',
            'columns' => [
                ['key' => 'module', 'label' => 'Module'],
                ['key' => 'category', 'label' => 'Category'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'count', 'label' => 'Count'],
            ],
        ],
        'attention-register' => [
            'title' => 'AIS Attention Register',
            'description' => 'Reviewable indicators that require human follow-up in the authoritative module.',
            'columns' => [
                ['key' => 'code', 'label' => 'Indicator Code'],
                ['key' => 'label', 'label' => 'Indicator'],
                ['key' => 'value', 'label' => 'Value'],
                ['key' => 'tone', 'label' => 'Severity'],
                ['key' => 'reviewInstruction', 'label' => 'Review Instruction'],
            ],
        ],
        'snapshot-trend' => [
            'title' => 'AIS Snapshot Trend',
            'description' => 'Reproducible trends from immutable AIS snapshots generated by the current actor.',
            'columns' => [
                ['key' => 'snapshotCode', 'label' => 'Snapshot'],
                ['key' => 'period', 'label' => 'Generated'],
                ['key' => 'activeEngagements', 'label' => 'Active Engagements'],
                ['key' => 'openCmsCases', 'label' => 'Open CMS Cases'],
                ['key' => 'overdueCmsCases', 'label' => 'Overdue CMS Cases'],
                ['key' => 'plannedPersonDays', 'label' => 'Planned Person-Days'],
            ],
        ],
    ];

    public function __construct(private readonly AisAggregationService $aggregation) {}

    /** @return array<string, mixed> */
    public function catalog(User $user): array
    {
        $this->authorize($user, 'ais.view');

        return [
            'reports' => collect(self::REPORTS)->map(fn (array $definition, string $code): array => [
                'code' => $code,
                'title' => $definition['title'],
                'description' => $definition['description'],
                'columns' => $definition['columns'],
            ])->values(),
            'formats' => [
                ['code' => 'csv', 'label' => 'CSV', 'mimeType' => 'text/csv'],
                ['code' => 'pdf', 'label' => 'PDF', 'mimeType' => 'application/pdf'],
            ],
            'scope' => $this->scopeSummary($user),
            'canExport' => $user->hasPermission('ais.export'),
            'professionalControls' => [
                'humanReviewRequired' => true,
                'sourceModulesRemainAuthoritative' => true,
                'automatedDecisionsDisabled' => true,
                'protectedDownloads' => true,
            ],
        ];
    }

    /** @return Collection<int, AisReportRun> */
    public function runs(User $user, int $limit = 50): Collection
    {
        $this->authorize($user, 'ais.view');

        return AisReportRun::query()
            ->with(['generator:id,name,employee_id', 'exports'])
            ->where('generated_by', $user->id)
            ->latest('generated_at')
            ->limit($limit)
            ->get();
    }

    public function show(User $user, int $runId): AisReportRun
    {
        $this->authorize($user, 'ais.view');
        $run = AisReportRun::query()->with(['generator:id,name,employee_id', 'exports'])->findOrFail($runId);
        abort_unless($this->runVisible($run, $user), 404, 'The AIS report is unavailable.');

        return $run;
    }

    /** @return array<string, mixed> */
    public function runData(AisReportRun $run): array
    {
        return [
            'id' => $run->id,
            'displayCode' => $run->display_code,
            'reportCode' => $run->report_code,
            'title' => $run->report_title,
            'sourceQueryVersion' => $run->source_query_version,
            'filters' => $run->filters,
            'scope' => $run->scope_snapshot,
            'rowCount' => $run->row_count,
            'checksumSha256' => $run->result_checksum_sha256,
            'generatedAt' => $run->generated_at?->toIso8601String(),
            'resultSnapshot' => $run->result_snapshot,
            'exports' => $run->exports->map(fn (AisReportExport $export): array => $this->exportData($export))->values()->all(),
        ];
    }

    /** @return array<string, mixed> */
    public function exportData(AisReportExport $export): array
    {
        return [
            'id' => $export->id,
            'runId' => $export->ais_report_run_id,
            'format' => strtolower($export->format),
            'versionNumber' => $export->version_number,
            'fileName' => $export->file_name,
            'mimeType' => $export->mime_type,
            'fileSize' => $export->file_size,
            'checksumSha256' => $export->checksum_sha256,
            'generatedAt' => $export->generated_at?->toIso8601String(),
        ];
    }

    /** @param array<string, mixed> $input */
    public function generate(Request $request, string $code, array $input): AisReportRun
    {
        $actor = $request->user();
        $this->authorize($actor, 'ais.view');
        $definition = self::REPORTS[$code] ?? null;
        abort_unless($definition, 404, 'The AIS report is unavailable.');
        $filters = validator($input, ['snapshotLimit' => ['nullable', 'integer', 'min:1', 'max:12']])->validate();
        $dashboard = $this->aggregation->dashboard($actor);
        $rows = $this->rows($code, $dashboard, (int) ($filters['snapshotLimit'] ?? 12));
        $snapshot = [
            'meta' => [
                'reportCode' => $code,
                'filters' => $filters,
                'scope' => $this->scopeSummary($actor),
                'dashboardVersion' => $dashboard['dashboardVersion'],
            ],
            'columns' => $definition['columns'],
            'rows' => $rows,
        ];
        $encoded = json_encode($snapshot, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

        $run = DB::transaction(fn (): AisReportRun => AisReportRun::query()->create([
            'report_code' => $code,
            'report_title' => $definition['title'],
            'source_query_version' => self::SOURCE_QUERY_VERSION,
            'filters' => $filters,
            'scope_snapshot' => $this->scopeSummary($actor),
            'result_snapshot' => $snapshot,
            'row_count' => count($rows),
            'result_checksum_sha256' => hash('sha256', $encoded),
            'generated_by' => $actor->id,
            'generated_at' => now(),
        ]));

        $this->record($request, 'ais.report.generated', "Generated {$definition['title']} with {$run->row_count} row(s).", $run, [
            'reportCode' => $code,
            'rowCount' => $run->row_count,
            'checksumSha256' => $run->result_checksum_sha256,
        ]);

        return $run->load(['generator:id,name,employee_id', 'exports']);
    }

    public function export(Request $request, int $runId, string $format): AisReportExport
    {
        $actor = $request->user();
        $this->authorize($actor, 'ais.export');
        $format = strtolower($format);
        abort_unless(in_array($format, ['csv', 'pdf'], true), 422, 'The export format is unsupported.');
        $run = $this->show($actor, $runId);
        $latest = AisReportExport::query()
            ->where('ais_report_run_id', $run->id)
            ->where('format', strtoupper($format))
            ->latest('version_number')
            ->first();
        if ($latest && Storage::disk('local')->exists($latest->storage_path)) return $latest;

        $version = ($latest?->version_number ?? 0) + 1;
        [$contents, $mimeType, $extension] = $format === 'csv'
            ? [$this->csv($run), 'text/csv; charset=UTF-8', 'csv']
            : [$this->pdf($run), 'application/pdf', 'pdf'];
        $checksum = hash('sha256', $contents);
        $name = Str::slug($run->report_title).'-'.$run->display_code.'-v'.$version.'.'.$extension;
        $path = 'ais/reports/'.$run->id.'/'.$format.'/v'.$version.'-'.$checksum.'.'.$extension;
        Storage::disk('local')->put($path, $contents);
        $export = AisReportExport::query()->create([
            'ais_report_run_id' => $run->id,
            'format' => strtoupper($format),
            'version_number' => $version,
            'file_name' => $name,
            'storage_path' => $path,
            'mime_type' => $mimeType,
            'file_size' => strlen($contents),
            'checksum_sha256' => $checksum,
            'generated_by' => $actor->id,
            'generated_at' => now(),
        ]);
        $this->record($request, 'ais.report.exported', "Generated {$format} export {$name}.", $export, [
            'runId' => $run->id,
            'format' => $format,
            'checksumSha256' => $checksum,
        ]);

        return $export->load('run');
    }

    public function download(Request $request, int $exportId): StreamedResponse
    {
        $actor = $request->user();
        $this->authorize($actor, 'ais.export');
        $export = AisReportExport::query()->with('run')->findOrFail($exportId);
        abort_unless($this->runVisible($export->run, $actor), 404, 'The AIS report export is unavailable.');
        abort_unless(Storage::disk('local')->exists($export->storage_path), 404, 'The private AIS report export file is unavailable.');
        $this->record($request, 'ais.report.downloaded', "Downloaded AIS report export {$export->file_name}.", $export, [
            'runId' => $export->ais_report_run_id,
            'checksumSha256' => $export->checksum_sha256,
        ]);

        return Storage::disk('local')->download($export->storage_path, $export->file_name, [
            'Content-Type' => $export->mime_type,
            'Cache-Control' => 'private, no-store',
            'X-Content-Type-Options' => 'nosniff',
            'X-Frame-Options' => 'DENY',
            'Referrer-Policy' => 'no-referrer',
            'X-AGIS-Checksum-SHA256' => $export->checksum_sha256,
        ]);
    }

    /** @return array<string, mixed> */
    public function alerts(User $user): array
    {
        $this->authorize($user, 'ais.view');
        $dashboard = $this->aggregation->dashboard($user);

        return [
            'generatedAt' => $dashboard['generatedAt'],
            'scope' => $dashboard['scope'],
            'alerts' => collect($dashboard['attention'])->map(fn (array $item): array => [
                ...$item,
                'sourceModule' => str_starts_with($item['code'], 'CMS_') ? 'CMS' : (str_starts_with($item['code'], 'EVIDENCE_') || str_starts_with($item['code'], 'FINDINGS_') ? 'AEMS' : 'ARMIS'),
                'reviewOnly' => true,
                'automaticDecision' => false,
                'reviewInstruction' => 'Open the authoritative module and apply its existing workflow.',
            ])->values(),
        ];
    }

    /** @param array<string, mixed> $dashboard @return list<array<string, mixed>> */
    private function rows(string $code, array $dashboard, int $snapshotLimit): array
    {
        return match ($code) {
            'portfolio-overview' => collect([
                ['indicator' => 'Approved IAP plans', 'value' => $dashboard['headline']['approvedIapPlans'], 'source' => 'IAP', 'interpretation' => 'Approved plans in the current scope.'],
                ['indicator' => 'Active engagements', 'value' => $dashboard['headline']['activeEngagements'], 'source' => 'AEMS', 'interpretation' => 'Engagements not in a terminal administrative status.'],
                ['indicator' => 'Findings awaiting review', 'value' => $dashboard['headline']['findingsAwaitingReview'], 'source' => 'AEMS', 'interpretation' => 'Requires review in AEMS; AIS takes no action.'],
                ['indicator' => 'Evidence requiring assessment', 'value' => $dashboard['headline']['evidenceAwaitingAssessment'], 'source' => 'AEMS', 'interpretation' => 'Evidence requires assessment or additional submission.'],
                ['indicator' => 'Open CMS cases', 'value' => $dashboard['headline']['openCmsCases'], 'source' => 'CMS', 'interpretation' => 'Cases not in closure or disposition terminal states.'],
                ['indicator' => 'Overdue CMS cases', 'value' => $dashboard['headline']['overdueCmsCases'], 'source' => 'CMS', 'interpretation' => 'Target date has passed and the case remains open.'],
                ['indicator' => 'Approved ARMIS assignments', 'value' => $dashboard['headline']['approvedArmisAssignments'], 'source' => 'ARMIS', 'interpretation' => 'Approved or locked resource assignments.'],
                ['indicator' => 'Planned person-days', 'value' => $dashboard['headline']['plannedPersonDays'], 'source' => 'ARMIS', 'interpretation' => 'Approved or locked planned effort.'],
            ])->all(),
            'status-register' => collect($dashboard['distributions'])
                ->flatMap(fn (array $items, string $category): Collection => collect($items)->map(fn (array $item): array => [
                    'module' => $this->moduleForCategory($category),
                    'category' => Str::of($category)->replace('_', ' ')->title()->toString(),
                    'status' => $item['label'],
                    'count' => $item['value'],
                ]))->values()->all(),
            'attention-register' => collect($dashboard['attention'])->map(fn (array $item): array => [
                'code' => $item['code'],
                'label' => $item['label'],
                'value' => $item['value'],
                'tone' => $item['tone'],
                'reviewInstruction' => 'Review in the authoritative module; AIS does not make a decision.',
            ])->all(),
            'snapshot-trend' => collect($dashboard['snapshotTrend'])->take(-$snapshotLimit)->all(),
            default => [],
        };
    }

    private function moduleForCategory(string $category): string
    {
        return match (true) {
            str_starts_with($category, 'engagement') => 'AEMS',
            str_starts_with($category, 'finding'), str_starts_with($category, 'evidence') => 'AEMS',
            str_starts_with($category, 'cms') => 'CMS',
            str_starts_with($category, 'armis') => 'ARMIS',
            default => 'AIS',
        };
    }

    private function csv(AisReportRun $run): string
    {
        $handle = fopen('php://temp', 'w+');
        $columns = $run->result_snapshot['columns'] ?? [];
        fputcsv($handle, array_map(fn (array $column): string => $this->safeCell($column['label']), $columns));
        foreach ($run->result_snapshot['rows'] ?? [] as $row) {
            fputcsv($handle, array_map(fn (array $column): string => $this->safeCell($row[$column['key']] ?? ''), $columns));
        }
        rewind($handle);
        $contents = stream_get_contents($handle);
        fclose($handle);

        return "\xEF\xBB\xBF".$contents;
    }

    private function safeCell(mixed $value): string
    {
        $value = is_scalar($value) || $value === null ? (string) $value : json_encode($value, JSON_UNESCAPED_UNICODE);

        return preg_match('/^\s*[=+\-@]/', $value) ? "'".$value : $value;
    }

    private function pdf(AisReportRun $run): string
    {
        $columns = $run->result_snapshot['columns'] ?? [];
        $rows = $run->result_snapshot['rows'] ?? [];
        $head = collect($columns)->map(fn (array $column): string => '<th>'.e($column['label']).'</th>')->implode('');
        $body = collect($rows)->map(fn (array $row): string => '<tr>'.collect($columns)->map(fn (array $column): string => '<td>'.e((string) ($row[$column['key']] ?? '')).'</td>')->implode('').'</tr>')->implode('');

        return Pdf::loadHTML('<html><body><h1>'.e($run->report_title).'</h1><p>'.$run->display_code.' | Checksum: '.e($run->result_checksum_sha256).'</p><table border="1" cellpadding="4"><thead><tr>'.$head.'</tr></thead><tbody>'.$body.'</tbody></table></body></html>')->output();
    }

    private function scopeSummary(User $user): array
    {
        return [
            'officeScope' => $user->hasGlobalOfficeAccess() ? 'ALL' : 'OWN_OFFICE',
            'officeId' => $user->hasGlobalOfficeAccess() ? null : $user->office_id,
            'engagementScope' => $user->hasGlobalEngagementAccess() ? 'ALL' : 'ASSIGNED',
            'generatedByUserId' => $user->id,
            'confidentiality' => [
                'confidential' => $user->hasPermission('documents.view_confidential') || $user->hasPermission('documents.view_restricted'),
                'restricted' => $user->hasPermission('documents.view_restricted'),
            ],
        ];
    }

    private function runVisible(AisReportRun $run, User $user): bool
    {
        return (int) data_get($run->scope_snapshot, 'generatedByUserId', 0) === (int) $user->id;
    }

    private function authorize(?User $user, string $permission): void
    {
        abort_unless($user?->is_active && ! $user->trashed() && $user->hasPermission($permission), 403, 'You do not have permission to access AIS reports.');
    }

    /** @param array<string, mixed> $metadata */
    private function record(Request $request, string $action, string $description, object $subject, array $metadata): void
    {
        ActivityRecorder::record($request, $action, $description, metadata: ['module' => 'AIS', 'recordType' => $subject::class, 'recordId' => $subject->getKey(), ...$metadata]);
        AuditLog::query()->create([
            'user_id' => $request->user()?->id,
            'action' => $action,
            'auditable_type' => $subject::class,
            'auditable_id' => $subject->getKey(),
            'new_values' => $metadata,
            'ip_address' => $request->ip(),
            'user_agent' => mb_substr((string) $request->userAgent(), 0, 1000),
            'metadata' => ['module' => 'AIS', ...$metadata],
        ]);
    }
}
