<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $order->order_code }}</title>
    <style>
        @page { margin: 36px 42px; }
        * { box-sizing: border-box; }
        body { color: #172554; font-family: DejaVu Sans, Arial, sans-serif; font-size: 10px; line-height: 1.55; }
        .header { border-bottom: 2px solid #075985; margin-bottom: 20px; padding-bottom: 12px; text-align: center; }
        .agency { color: #0369a1; font-size: 11px; font-weight: 700; text-transform: uppercase; }
        h1 { color: #0f172a; font-size: 19px; margin: 7px 0 2px; }
        .code { color: #475569; font-weight: 700; }
        .meta { border-collapse: collapse; margin-bottom: 18px; width: 100%; }
        .meta td { border: 1px solid #cbd5e1; padding: 7px 9px; vertical-align: top; width: 25%; }
        .label { color: #64748b; display: block; font-size: 7px; font-weight: 700; letter-spacing: .05em; text-transform: uppercase; }
        h2 { border-left: 3px solid #0284c7; color: #0f172a; font-size: 11px; margin: 15px 0 6px; padding-left: 7px; }
        .text { color: #334155; white-space: pre-line; }
        table.team { border-collapse: collapse; margin-top: 6px; width: 100%; }
        .team th { background: #0c4a6e; color: white; font-size: 8px; padding: 6px; text-align: left; }
        .team td { border: 1px solid #cbd5e1; padding: 6px; vertical-align: top; }
        .certification { border: 1px solid #94a3b8; margin-top: 24px; padding: 12px; }
        .footer { border-top: 1px solid #cbd5e1; color: #64748b; font-size: 7px; margin-top: 24px; padding-top: 7px; text-align: right; }
    </style>
</head>
<body>
    <header class="header">
        <div class="agency">{{ $configuration['organizationName'] }} · {{ $configuration['systemName'] }}</div>
        <h1>Audit Engagement Order</h1>
        <div class="code">{{ $order->order_code }} · Approved Version {{ $version->version_number }}</div>
    </header>

    <table class="meta">
        <tr>
            <td><span class="label">Engagement</span>{{ $engagement->engagement_code }}</td>
            <td><span class="label">Effectivity</span>{{ $version->effectivity_date?->format('F j, Y') ?? 'Not specified' }}</td>
            <td><span class="label">Planned start</span>{{ $version->planned_start_date?->format('F j, Y') ?? 'Not specified' }}</td>
            <td><span class="label">Planned end</span>{{ $version->planned_end_date?->format('F j, Y') ?? 'Not specified' }}</td>
        </tr>
        <tr>
            <td colspan="2"><span class="label">Auditee office(s)</span>{{ $engagement->offices->pluck('name')->join(', ') }}</td>
            <td colspan="2"><span class="label">Audit area(s)</span>{{ $engagement->auditAreas->pluck('name')->join(', ') }}</td>
        </tr>
    </table>

    <h2>Authority</h2>
    <div class="text">{{ $version->authority }}</div>

    <h2>Engagement Objectives</h2>
    <div class="text">{{ $version->objectives }}</div>

    <h2>Scope</h2>
    <div class="text">{{ $version->scope }}</div>

    <h2>Authorized Audit Team</h2>
    <table class="team">
        <thead>
            <tr><th>Role</th><th>Employee</th><th>Position</th><th>Person-days</th><th>Assignment dates</th></tr>
        </thead>
        <tbody>
        @foreach(($version->team_snapshot ?? []) as $member)
            <tr>
                <td>{{ str($member['role'] ?? '')->replace('_', ' ')->title() }}</td>
                <td>{{ data_get($member, 'user.name', '—') }}</td>
                <td>{{ data_get($member, 'user.position', '—') }}</td>
                <td>{{ number_format((float) ($member['plannedPersonDays'] ?? 0), 2) }}</td>
                <td>{{ $member['assignedFrom'] ?? '—' }} to {{ $member['assignedUntil'] ?? '—' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <div class="certification">
        This PDF was generated from the approved immutable AEO version recorded
        in AGIS. Later team or engagement changes do not alter this version.
        <br><br>
        <strong>Approved by:</strong> {{ $approvalEvent?->actor?->name ?? '—' }}
        @if($approvalEvent?->created_at)
            on {{ $approvalEvent->created_at->format('F j, Y g:i A') }}
        @endif
        @if($issueEvent?->created_at)
            <br><strong>Issued by:</strong> {{ $issueEvent?->actor?->name ?? '—' }}
            on {{ $issueEvent->created_at->format('F j, Y g:i A') }}
        @endif
    </div>

    <div class="footer">
        Generated by AGIS · {{ now()->format('F j, Y g:i A') }}
    </div>
</body>
</html>
