<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $run->report_title }}</title>
    <style>
        @page { margin: 22px 24px; }
        * { box-sizing: border-box; }
        body { margin: 0; color: #1e293b; font-family: DejaVu Sans, Arial, sans-serif; font-size: 9px; line-height: 1.4; }
        .header { border-bottom: 2px solid #075985; margin-bottom: 14px; padding-bottom: 10px; text-align: center; }
        .agency { color: #075985; font-size: 11px; font-weight: 700; text-transform: uppercase; }
        h1 { color: #0f172a; font-size: 17px; margin: 5px 0 2px; }
        .description { color: #64748b; margin: 0 auto; max-width: 760px; }
        .meta { margin: 0 0 14px; width: 100%; }
        .meta td { background: #f1f5f9; border: 1px solid #cbd5e1; padding: 5px 7px; width: 25%; }
        .meta strong { color: #475569; display: block; font-size: 7px; letter-spacing: .04em; text-transform: uppercase; }
        table.data { border-collapse: collapse; page-break-inside: auto; table-layout: auto; width: 100%; }
        .data th { background: #0c4a6e; border: 1px solid #075985; color: white; font-size: 7px; padding: 5px; text-align: left; text-transform: uppercase; }
        .data td { border: 1px solid #cbd5e1; padding: 5px; vertical-align: top; word-break: break-word; }
        .data tr:nth-child(even) td { background: #f8fafc; }
        .data tr { page-break-inside: avoid; }
        .empty { border: 1px solid #cbd5e1; color: #64748b; padding: 18px; text-align: center; }
        .footer { border-top: 1px solid #cbd5e1; color: #64748b; font-size: 7px; margin-top: 12px; padding-top: 6px; text-align: right; }
    </style>
</head>
<body>
<header class="header">
    <div class="agency">AGIS · ARMIS</div>
    <h1>{{ $run->report_title }}</h1>
    <p class="description">Generated from immutable ARMIS-5A report snapshot {{ $run->display_code }}.</p>
</header>

@if(count($meta))
    <table class="meta">
        @foreach(array_chunk($meta, 4) as $group)
            <tr>
                @foreach($group as $item)
                    <td><strong>{{ $item['label'] }}</strong>{{ $item['value'] }}</td>
                @endforeach
                @for($index = count($group); $index < 4; $index++)
                    <td></td>
                @endfor
            </tr>
        @endforeach
    </table>
@endif

@if(count($rows))
    <table class="data">
        <thead>
        <tr>
            @foreach($columns as $column)
                <th>{{ $column['label'] }}</th>
            @endforeach
        </tr>
        </thead>
        <tbody>
        @foreach($rows as $row)
            <tr>
                @foreach($columns as $column)
                    <td>{{ $row[$column['key']] ?? '—' }}</td>
                @endforeach
            </tr>
        @endforeach
        </tbody>
    </table>
@else
    <div class="empty">No records matched this report.</div>
@endif

<footer class="footer">
    Generated by AGIS on {{ $run->generated_at?->format('F j, Y g:i A') }} · Checksum {{ $run->result_checksum_sha256 }}
</footer>
</body>
</html>
