<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $report->report_code }} - {{ $snapshot['title'] }}</title>
    <style>
        @page { margin: 72px 62px 68px; }
        body { color: #1e293b; font-family: DejaVu Sans, sans-serif; font-size: 10px; line-height: 1.55; }
        h1, h2, h3, p { margin: 0; }
        h1 { color: #0f3f70; font-size: 22px; line-height: 1.25; }
        h2 { border-bottom: 1px solid #cbd5e1; color: #0f3f70; font-size: 15px; margin: 24px 0 9px; padding-bottom: 5px; }
        h3 { color: #334155; font-size: 11px; margin: 11px 0 4px; }
        .header { border-bottom: 3px solid #0f5f9a; margin-bottom: 24px; padding-bottom: 14px; }
        .eyebrow { color: #64748b; font-size: 8px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; }
        .meta { color: #475569; margin-top: 8px; }
        .badge { background: #e0f2fe; border: 1px solid #bae6fd; border-radius: 3px; color: #075985; display: inline-block; font-size: 8px; font-weight: bold; margin-top: 8px; padding: 3px 7px; }
        .section-content, .finding-text { white-space: pre-wrap; }
        .finding { border: 1px solid #cbd5e1; margin: 12px 0; padding: 12px; page-break-inside: avoid; }
        .finding-code { color: #0369a1; font-size: 8px; font-weight: bold; text-transform: uppercase; }
        .grid { width: 100%; }
        .grid td { padding: 4px 8px 4px 0; vertical-align: top; width: 50%; }
        .label { color: #64748b; font-size: 8px; font-weight: bold; text-transform: uppercase; }
        .recommendation { background: #f8fafc; border-left: 3px solid #38bdf8; margin-top: 8px; padding: 8px; }
        .footer { bottom: -48px; color: #64748b; font-size: 8px; left: 0; position: fixed; right: 0; text-align: center; }
    </style>
</head>
<body>
    <div class="footer">
        {{ $report->report_code }} · Version {{ $versionNumber }} ·
        {{ str_replace('_', ' ', $snapshot['reportStage']) }} · Generated by AGIS
    </div>

    <header class="header">
        <p class="eyebrow">{{ $configuration['organization_name'] ?? 'City Internal Audit Service' }}</p>
        <h1>{{ $snapshot['title'] }}</h1>
        <p class="meta">
            {{ $report->report_code }} · {{ $engagement->engagement_code }} ·
            Version {{ $versionNumber }}
        </p>
        <span class="badge">{{ str_replace('_', ' ', $snapshot['reportStage']) }}</span>
    </header>

    <h2>Executive Summary</h2>
    <p class="section-content">{{ $snapshot['executiveSummary'] }}</p>

    @foreach ($snapshot['sections'] as $section)
        <h2>{{ $section['sequenceNumber'] }}. {{ $section['title'] }}</h2>
        <p class="section-content">{{ $section['content'] }}</p>
    @endforeach

    <h2>Included Findings</h2>
    @foreach ($snapshot['findings'] as $finding)
        <article class="finding">
            <p class="finding-code">{{ $finding['findingCode'] }}</p>
            <h3>{{ $finding['sequenceNumber'] }}. {{ $finding['title'] }}</h3>
            <table class="grid">
                <tr>
                    <td>
                        <span class="label">Risk rating</span><br>
                        {{ $finding['riskRating']['label'] ?? 'Not specified' }}
                    </td>
                    <td>
                        <span class="label">Responsible office</span><br>
                        {{ $finding['responsibleOffice']['name'] ?? 'Not specified' }}
                    </td>
                </tr>
            </table>
            @foreach ([
                'Criteria' => $finding['criteria'],
                'Condition' => $finding['condition'],
                'Cause' => $finding['cause'],
                'Effect' => $finding['effect'],
            ] as $label => $value)
                <h3>{{ $label }}</h3>
                <p class="finding-text">{{ $value }}</p>
            @endforeach
            @foreach ($finding['recommendations'] as $recommendation)
                <div class="recommendation">
                    <strong>{{ $recommendation['recommendationCode'] }}</strong><br>
                    {{ $recommendation['recommendation'] }}
                    @if ($recommendation['targetImplementationDate'])
                        <br><span class="label">Target:</span>
                        {{ $recommendation['targetImplementationDate'] }}
                    @endif
                </div>
            @endforeach
        </article>
    @endforeach

    @if ($snapshot['reportStage'] === 'FINAL_REPORT')
        <h2>Report Authority and Distribution</h2>
        <p><span class="label">Approving authority</span><br>{{ $snapshot['approvingAuthority'] }}</p>
        <p style="margin-top: 8px">
            <span class="label">Controlled recipients</span><br>
            {{ count($snapshot['recipients']) }} recipient record(s) preserved with this version.
        </p>
    @endif
</body>
</html>
