<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $run->report_title }}</title>
    <style>
        @page { margin: 22px; }
        body { color: #1f2937; font-family: DejaVu Sans, sans-serif; font-size: 9px; }
        h1 { color: #0f3d68; font-size: 17px; margin: 0 0 4px; }
        .meta { color: #475569; margin-bottom: 12px; }
        .meta span { margin-right: 16px; }
        table { border-collapse: collapse; width: 100%; }
        th { background: #0f5d92; color: #fff; font-weight: bold; }
        th, td { border: 1px solid #cbd5e1; padding: 5px; vertical-align: top; }
        tr:nth-child(even) td { background: #f8fafc; }
        .footer { color: #64748b; font-size: 8px; margin-top: 10px; }
    </style>
</head>
<body>
    <h1>{{ $run->report_title }}</h1>
    <div class="meta">
        <span>Run: {{ $run->display_code }}</span>
        <span>Generated: {{ $run->generated_at?->format('Y-m-d H:i:s T') }}</span>
        <span>Rows: {{ $run->row_count }}</span>
        <span>Snapshot: {{ $run->result_checksum_sha256 }}</span>
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($columns as $column)
                    <th>{{ $column['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($columns as $column)
                        <td>{{ is_array($row[$column['key']] ?? null) ? json_encode($row[$column['key']], JSON_UNESCAPED_UNICODE) : ($row[$column['key']] ?? '') }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($columns) }}">No records matched the authorized scope and filters.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by AGIS CMS. This private report is reproducible from the immutable snapshot identified above.</div>
</body>
</html>
